// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8Dy33djq5gCcvkDH0DZAMiCJKmt_pe0',
    appId: '1:342733035145:web:4006e170d0da06a38e1858',
    messagingSenderId: '342733035145',
    projectId: 'auth-3884d',
    authDomain: 'auth-3884d.firebaseapp.com',
    storageBucket: 'auth-3884d.appspot.com',
    measurementId: 'G-TFYBPSFP72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_uixnSlYQRn7Hb16D_NR-dQXEfCG5W8',
    appId: '1:342733035145:android:1c79d9446f55ff828e1858',
    messagingSenderId: '342733035145',
    projectId: 'auth-3884d',
    storageBucket: 'auth-3884d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb2AgH6FPXHm-sqPGJmcoCHTlnY4ExZlQ',
    appId: '1:342733035145:ios:08ec5015e898013f8e1858',
    messagingSenderId: '342733035145',
    projectId: 'auth-3884d',
    storageBucket: 'auth-3884d.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb2AgH6FPXHm-sqPGJmcoCHTlnY4ExZlQ',
    appId: '1:342733035145:ios:60dcdf7347a64c548e1858',
    messagingSenderId: '342733035145',
    projectId: 'auth-3884d',
    storageBucket: 'auth-3884d.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
